### ISSUE TITLE
Questions related to data format

### ISSUE THREAD

**Issue by ghost** [CancerDataAggregator/transform#12]
- [ ] Standardize names of entities. Use CamelCase
- [x] Only fields that are in the data model are included. Exception is Files
- [ ] Instead of having an object for `identifier` could we add a prefix to the identifier?
- [ ] Negative `days_to_birth`?
- [ ] Treatment?
- [ ] Any way to track identical Diagnoses?

Identifier proposal

Instead of
```
  "identifier":
    - "value": "0067a0e0-63d8-11e8-bcf1-0a2705229b82"
      "system": "PDC"
```

```
PDC-0067a0e0-63d8-11e8-bcf1-0a2705229b82
```

**Comment by druth314** [comment]
standardize names of entities: currently done based on CCDH recommendations.
only fields in data model are included: Currently how it works - also will be that way when we switch to reading the YML file for mapping.
keeping identifier as is
negative days to birth - keeping as is for now. that is what is returned from GDC/PDC
Treatment - currently in output - will be updated with issue #36 and issue #61 
identical Diagnoses? - as of now not yet. Will be followed closer when we decide how/what data to merge for R2
