### ISSUE TITLE
Could `log.distinct` work on lists

### ISSUE THREAD

**Issue by kaushik-work** [CancerDataAggregator/transform#22]
`log.distinct(table, field)` expects `table` to be a dict. Could it recurse into a list of dicts too?

**Comment by pshapiro4broad** [comment]
> log.distinct(table, field) expects table to be a dict. Could it recurse into a list of dicts too?

Do you mean `log.distinct([dict1, dict2, dict3], field)` instead of

**Comment by pshapiro4broad** [comment]
Should be trivial to do if we move the table to the end of the parameter list, since we can use varargs at that point.
