### ISSUE TITLE
Fix: Modify Extract tools for both PDC and GDC to reflect needed File fields

### ISSUE THREAD

**Issue by YeastCell** [CancerDataAggregator/transform#33]
fyi @kaushik-work 
As per @kreinold's suggestion, these are the fields that should be included:
https://github.com/CancerDataAggregator/transform/blob/5822d37d8ce14a008556016f115ebe9aab7f9f45/tests/steps/gdc_pdc_TCGA-E2-A10A_merged.yaml#L82-L91
Here is how this would map in both systems:

GDC (from the cases endpoint):
``` 
id: files.file_id 
identifier: files.submitter_id 
associated_project: project.project_id
data_category: files.data_category
data_type: files.data_type
label: @kreinold 
byte_size:  files.file_size
checksum: files.md5sum 
file_format: files.data_format ???
```
PDC:
```
id: fileMetadata.file_id
identifier: fileMetadata.file_submitter_id
associated_project: case.project_submitter_id --> this can get included in the transformation step
data_category: fileMetadata.data_category
data_type: fileMetadata.file_type ???
label: @kreinold 
byte_size:  fileMetadata.file_size
checksum: fileMetadata.md5sum 
file_format: fileMetadata.file_format
```

**Comment by druth314** [comment]
The only field currently missing is the file_format field in GDC. I believe it may correspond to the data_format field in GDC.
All fields in PDC are present.

**Comment by druth314** [comment]
Fields have been added to the extraction/transform code. Must add fields to the test files as well to pass tests
