### ISSUE TITLE
Tuple vs List issue in test case diff

### ISSUE THREAD

**Issue by kghose** [CancerDataAggregator/transform#43]
Looking at the diff output (say here: https://github.com/CancerDataAggregator/transform/runs/1930743902#step:6:107) we see that the diff is failing because one data type is a list and the other is a tuple. Is there a way to resolve this? We were unable to determine why the two data types are different.

**Comment by pshapiro4broad** [comment]
The problem is that the YAML is generating a list and the transform code is generating a tuple. I think they render the same in json/yaml. I can modify the yaml to generate a tuple instead of a list, but before that I'm going to look at the transform code and see why a tuple is being generated.
