### ISSUE TITLE
Harmonize Patient fields

### ISSUE THREAD

**Issue by YeastCell** [CancerDataAggregator/transform#52]
It appears that there is still demographics information with both lower cases and upper case letters.

The next query returns a lot less results than it should be:

```
SELECT *
FROM gdc-bq-sample.cda_mvp.v2,
UNNEST(ResearchSubject) AS _ResearchSubject,
UNNEST(_ResearchSubject.Specimen) AS _Specimen
WHERE (_Specimen.source_material_type = 'Primary Tumor' and sex = "Female")
```

Only when ```Female``` is replaced with ```female```, it returns many more results.
However, we then still lack those that we get with the first query.

**Comment by druth314** [comment]
I made a fix for this in the most recent branch that I pushed. GDC has all data in lowercase letters while PDC has a capitalization format. I made everything lowercase for simplicity in my latest branch but have not uploaded a table
