### ISSUE TITLE
Incorporate PDC aliquots, aliquot_run_metadata_ids, study ids, and embargo date

### ISSUE THREAD

**Issue by anniekuan** [CancerDataAggregator/transform#60]
For PDC, we noticed that aliquots aren't currently incorporated. Additionally, we need aliquot_run_metadata_ids in order to create some of our derived tables (e.g. protein abundance log2 ratio). We also need the pdc study ids and embargo date.

**Comment by druth314** [comment]
It looks like we do not currently extract PDC - aliquots. Must alter pdc_query_lib.py to do so.
