### ISSUE TITLE
Resolve missing fields in diagnoses, diagnoses.treatments

### ISSUE THREAD

**Issue by anniekuan** [CancerDataAggregator/transform#61]
diagnoses, diagnoses.treatments have missing fields (and diagnoses.annotations isn't included), and the demographic data is incomplete. We also incorporate family_histories, exposures, follow_ups, follow_ups.molecular_tests.

**Comment by druth314** [comment]
Inclusion of family_histories, exposures, follow_ups, and follow_ups.molecular tests will be postponed for a later release (Perhaps R2.1?)
